# Introduction

This project is for a bank to detect it's customer churn. The bank has seen that there was a lot of churn over the last 6 months and it wants us to create a model that can predict whether, given certain specific details about a customer, would that customer stay or leave the bank.

This model has been created using Artificial Neural Network to classify whether a customer would stay or leave the bank.

A value of "True" means that the customer would leave the bank.
A value of "False" means that the customer would stay with the bank.

# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [41]:
tf.__version__  # checking the version of TensorFlow

'2.15.0'

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Part 1 - Data Preprocessing

### Importing the dataset

In [42]:
# Creating the X and y data arrays after reading the dataset

dataset = pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2]= le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
# We will use StandardScaler for standardizing everything in X_train and X_test

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
# We will create a variable for the ANN as an object of the Sequential class

ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [19]:
# Using rectifier as the activation function here

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the second hidden layer

In [18]:
# Using rectifier as the activation again

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [33]:
# Final output layer will have sigmoid activation (binary) and unit would be 1 as we want only 1 result set as "exited"
# if it was categorical classification we would've used softmax activation

ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [34]:
# We will use Stochastic Gradient Descent (adam) optimizer
# We will use binary_crossentropy by default as it is binary classification. For categorical we would've used categorical_crossentropy

ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

### Training the ANN on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6574 - accuracy: 0.8309
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5972 - accuracy: 0.8080
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5506 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5143 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4627 - accuracy: 0.8185
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4456 - accuracy: 0.8646
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4304 - accuracy: 0.8662
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4196 - accuracy: 0.8633
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4082 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Test**

Use the ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [36]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 134ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!


### Predicting the Test set results

In [37]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [38]:
# Using confusion_matrix and accuracy_score

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1525   70]
 [ 207  198]]


0.8615

# CONCLUSION

This ANN model helps the bank predict, with 86% accuracy, whether a customer is bound to leave or be retained by the bank.

# Streamlit App

In [47]:
from keras.models import Sequential

ann.save('customer_churn_model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [48]:
# Download the model file
files.download('customer_churn_model.h5')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>